### ISSUE TITLE
JB2 Image requires 0 images from shared library

### ISSUE THREAD

**Issue by jsbien** [trufanov-nok/djvudict#1]
On another document your programs works, so I assume it has been build correctly (Debian buster).
For the document created with didjvu using  "-p 26" parameter I get:
JB2 Image requires 0 images from shared library which wasn't providedReading page Info: w:3292 h:5471 ver:0.24 dpi:600
and the enclosed statistics
[stats.log](https://github.com/trufanov-nok/djvudict/files/4369710/stats.log)

**Comment by trufanov-nok** [comment]
Sorry, I didn't notice your post before.
Could you upload the djvu file which produce this error somewhere?

**Comment by jsbien** [comment]
No problem, I'm not in a hurry.
The size is 9 MB. Can it be uploaded here or better to place it temporarily elsewhere?

**Comment by trufanov-nok** [comment]
Whatever you want or will work. You can upload it to dropmefiles.com for example

**Comment by jsbien** [comment]
https://www.dropbox.com/s/asqsn140i1bokvl/Zaborowski1wyd.djvu?dl=0
Dropbox try to open the file and fails, but you can download it.

**Comment by trufanov-nok** [comment]
I'll check the code - perhaps it stuck somewhere because I expected more details in log file for such document, but technically the results are correct.
This document contain only BG44 chunks. And there are no any Sjbz/Djbz dictionaries - so, nothing to extract and analyze. Basically this document is just a set of non-processed scans and functionally equal to the folder with jpeg images. If you open it in DjView and switch to View/Display/Background and View/Display/Foreground you'll see that there is nothing in Foreground.

I never used didjvu. As I understood, didjvu expected to automatically separate background and text and then encode text as foreground? If it so, then it failed.

**Comment by jsbien** [comment]
On Mon, May 04 2020 at 10:11 -07, Alexander Trufanov wrote:
> I'll check the code - perhaps it stuck somewhere because I expected
> more details in log file for such document, but technically the
> results are correct.  This document contain only BG44 chunks. And
> there are no any Sjbz/Djbz dictionaries - so, nothing to extract and
> analyze. Basically this document is just a set of non-processed scans
> and functionally equal to the folder with jpeg images. If you open it
> in DjView and switch to View/Display/Background and
> View/Display/Foreground you'll see that there is nothing in
> Foreground.

I should have noticed it...

>
> I never used didjvu. As I understood, didjvu expected to automatically
> separate background and text and then encode text as foreground? If it
> so, then it failed.

Yes.

It has a lot of options, I will make another try in a few days.

Regards - Janusz

-- 
             ,   
Janusz S. Bien
emeryt (emeritus)
https://sites.google.com/view/jsbien

**Comment by jsbien** [comment]
It appeared I've uploaded the wrong file. This is the intended one:
https://www.dropbox.com/sh/qtxyvy0onl1libp/AABlVxvttvg_kIyceubzzIEia?dl=0

**Comment by trufanov-nok** [comment]
Are you sure it depends on  "-p 26" parameter? I suspect it should not matter, Could you send same doc encoded with -p 20 or anything like that for example...

**Comment by trufanov-nok** [comment]
Well, I've managed to install both gamera and didjvu to find out what exactly didjvu is doing.

It seems it separates image to text and background layers, then encodes text layer with cjb2 (if single page) or minidjvu (if bundled), then extracts Sjbz and optionally Djbz from resulted doc. After that didjvu encodes both original background layer and text layer with c44 to images in IW44 format. The trick is that very small subsampling value is used for text layer. And at last didjvu combines Djbz, Sjbz, IW44 encoded background layer as BG44 chunk and IW44-encoded text layer as FG44 chunk to make a single document.

According to some book:

> The background contains paper texture (to preserve the original look-and-feel of the document) and pictures, while the foreground contains text and drawings. The foreground is represented as a bi-level image, called foreground mask, encoded in JB2 where black denotes the foreground pixels and white the background ones. **Foreground colors can be represented** by specifying the color of each foreground shape separately, **or as a small image, sub-sampled** with a factor ranging from 1 to 12 (usually 12: smaller values do not significantly increase quality), that is scaled up to the original size of the document and drawn on the background image. The background image is obtained through progressive IW44 refinements, scaled down with a sub-sampling factor between | and 12 (usually 3, smaller if high-quality pictures are to be represented, higher if no pictures are present).

So this is one of the ways to use pasterized text layer instead of b/w text. But instead of setting one of indexed colors to each letter in JB2 shapes dictionary the colors are supplied by low-sampled image.

We never make djvu docs in a such way. We usually delete "paper texture" (using white background) and keeping only images in it. And text goes to b/w. In case it's a colored text the pasterezation and indexed colors are used in document (as i think it's done in Scan Tailor Advanced). And in case text must be preserved "as is" it can be just added to background layer as image with same subsample rate as it's done in Scan Tailor Universal.
And this way of setting colors for text layer is a compromise between mentioned two. I wasn't aware of it. Perhaps I shall try to add a few new features in ScanTailor Universal to address the "paper texture" option and this way of pasterization.

**Comment by trufanov-nok** [comment]
As for the djvudict issue - I'll fix it soon. The problem was in assertion that Djbz can't be empty. It seems it can be on practice. For example if you have 11 paged doc with "-p 5" There will be 1 Djbz for 11th page and it will be empty. minidjvu isn't smart enough to omit saving empty distributed dictionaries.
And in your document Djbz was empty for some reason too. djvu dumb shows:
```FORM:DJVI [13] {Altpolnische_0002.iff} [I]
      Djbz [1]          JB2 shared dictionary```
[1] - is a size of chunk in bytes.

I'll update the djvudict today and hopefully rebuild windows binary too.

**Comment by trufanov-nok** [comment]
Updated version: https://github.com/trufanov-nok/djvudict/releases/tag/0.0.2

**Comment by jsbien** [comment]
Thanks for all your work and the extensive comments. I will make some new experiments in a few days.

**Comment by jsbien** [comment]
I got now some reasonable results. Thank you very much for your help.

**Comment by jsbien** [comment]
What is the source of the quotation of May 8th? Is it realy a book?

**Comment by trufanov-nok** [comment]
> What is the source of the quotation of May 8th? Is it realy a book?

Yes, I found it in "Automatic Digital Document Processing and Management: Problems, Algorithms and Techniques" by Stefano Ferilli, 2011 via books.google.com. Looks like the pirated copy may be viewed online [here](http://bookre.org/reader?file=1171880&pg=69) too.

**Comment by jsbien** [comment]
Thanks. I found it in my library. Looks interesting.
